# Generated by Django 5.0.3 on 2024-03-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_menu_created_at_menu_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='order',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
