# Generated by Django 5.0.3 on 2024-03-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0007_alter_category_options_remove_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='hel', max_length=100),
            preserve_default=False,
        ),
    ]
