# Generated by Django 5.0.3 on 2024-03-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0005_menu_submenu_head_alter_menu_slug_alter_menu_title_and_more'),
        ('site_app', '0012_alter_post_description'),
    ]

    operations = [
    ]
