# Generated by Django 5.0.3 on 2024-03-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0014_remove_menu_submenu_head_menu_menu_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['order']},
        ),
    ]
