# Generated by Django 5.0.3 on 2024-03-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0021_menuitem_menuitemcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['heading', 'name'], 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='menuitemcontent',
            options={'ordering': ['menu_item', 'created_at'], 'verbose_name': 'Menu Item Content', 'verbose_name_plural': 'Menu Items Content'},
        ),
    ]
