# Generated by Django 5.0.3 on 2024-03-14 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0022_alter_menuitem_options_alter_menuitemcontent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemcontent',
            name='menu_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='site_app.menuitem'),
        ),
    ]
