# Generated by Django 5.0.3 on 2024-03-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0008_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_url',
            field=models.FileField(blank=True, null=True, upload_to='uploads/files/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
    ]
