# Generated by Django 5.0.3 on 2024-03-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0009_alter_post_file_url_alter_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='web_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
