# Generated by Django 5.0.3 on 2024-03-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0010_post_web_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.ImageField(null=True, upload_to='uploads/events/'),
        ),
    ]
