# Generated by Django 5.0.3 on 2024-03-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0015_alter_menu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(max_length=25, unique=True),
        ),
    ]
