# Generated by Django 5.0.3 on 2024-03-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0016_alter_menu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
