# Generated by Django 5.0.3 on 2024-03-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0017_alter_menu_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('A', 'Announcements'), ('B', 'News'), ('C', 'Quick Links')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
