# Generated by Django 5.0.3 on 2024-03-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0019_download'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='download',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
