# Generated by Django 5.0.3 on 2024-03-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0020_delete_category_alter_download_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('A', 'Announcements'), ('B', 'News'), ('C', 'Quick Links'), ('D', 'News Flash')], max_length=1),
        ),
    ]
