# Generated by Django 5.0.3 on 2024-03-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0021_alter_post_post_type'),
        ('site_app', '0022_alter_menuitem_options_alter_menuitemcontent_options'),
    ]

    operations = [
    ]
