# Generated by Django 5.0.3 on 2024-03-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0023_alter_menuitemcontent_menu_item'),
        ('site_app', '0023_merge_20240314_1725'),
    ]

    operations = [
    ]
