# Generated by Django 5.0.3 on 2024-03-15 11:12

import site_app.models
import site_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0024_merge_20240314_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=site_app.models.custom_image_filename)),
                ('caption', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='download',
            name='file',
            field=models.FileField(upload_to='uploads/downloads/', validators=[site_app.validators.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='download',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
